# Generated by Django 1.11.5 on 2018-01-08 14:14
from __future__ import unicode_literals

from decimal import Decimal

import django.contrib.postgres.fields.hstore
import django.core.validators
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("product", "0043_auto_20171207_0839")]

    operations = [
        migrations.AlterField(
            model_name="attributechoicevalue",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="attributechoicevalue",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=128)
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product.Category",
            ),
        ),
        migrations.AlterField(
            model_name="category", name="slug", field=models.SlugField()
        ),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                relate