# Generated by Django 2.2.1 on 2019-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("product", "0092_auto_20190507_0309")]

    operations = [
        migra