# Generated by Django 3.1 on 2020-08-10 14:15

from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0120_au