# Generated by Django 3.1 on 2020-10-30 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0136_add_attribute_type_and_page_to_attribute_relation"),
        ("attribute", "0001_initial"),
    ]

    state_operations = [
        migrations.AlterUniqueTogether(
            name="assignedproductattribute",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="assignedproductattribute",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="as