# Generated by Django 1.10.5 on 2017-02-06 10:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shipping", "0003_auto_20170116_0700")]

    operations = [
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={
                "verbose_name": "shipping method",
                "verbose_name_plural": "shipping methods",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingmethodcountry",
            options={
                "verbose_name": "shipping method country",
                "verbose_name_plural": "shipping method countries",
            },
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="shippingmethodcountry",
            name="country_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Rest of World"),
                    ("AF", "Afghanistan"),
                    ("AX", "\xc5land Islands"),
                    ("AL", "Albania"),
                    ("DZ", "Algeria"),
                    ("AS", "American Samoa"),
                    ("AD", "Andorra"),
                    ("AO", "Angola"),
                    ("AI", "Anguilla"),
                    ("AQ", "Antarctica"),
                    ("AG", "Antigua and Barbuda"),
                    ("AR", "Argentina"),
                    ("AM", "Armenia"),
                    ("AW", "Aruba"),
                    ("AU", "Australia"),
                    ("AT", "Austria"),
                    ("AZ", "Azerbaijan"),
                    ("BS", "Bahamas"),
                    ("BH", "Bahrain"),
                    ("BD", "Bangladesh"),
                    ("BB", "Barbados"),
                    ("BY", "Belarus"),
                    ("BE", "Belgium"),
                    ("BZ", "Belize"),
                    ("BJ", "Benin"),
                    ("BM", "Bermuda"),
                    ("BT", "Bhutan"),
                    ("BO", "Bolivia"),
                    ("BQ", "Bonaire, Sint Eustatius and Saba"),
                    ("BA", "Bosnia and Herzegovina"),
                    ("BW", "Botswana"),
                    ("BV", "Bouvet Island"),
                    ("BR", "Brazil"),
                    ("IO", "British Indian Ocean Territory"),
                    ("BN", "Brunei"),
                    ("BG", "Bulgaria"),
                    ("BF", "Burkina Faso"),
                    ("BI", "Burundi"),
                    ("CV", "Cabo Verde"),
                    ("KH", "Cambodia"),
                    ("CM", "Cameroon"),
                    ("CA", "Canada"),
                    ("KY", "Cayman Islands"),
                    ("CF", "Central African Republic"),
                    ("TD", "Chad"),
                    ("CL", "Chile"),
                    ("CN", "China"),
                    ("CX", "Christmas Island"),
                    ("CC", "Cocos (Keeling) Islands"),
                    ("CO", "Colombia"),
                    ("KM", "Comoros"),
                    ("CG", "Congo"),
    