# Generated by Django 1.11.5 on 2018-01-08 14:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shipping", "0007_auto_20171129_1004")]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingmethodcountry",
            name="country_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Rest of World"),
                    ("AF", "Afghanistan"),
                    ("AX", "Åland Islands"),
                    ("AL", "Albania"),
                    ("DZ", "Algeria"),
                    ("AS", "American Sa