# Generated by Django 3.2.13 on 2022-05-27 12:23

from django.db import migrations

from .. import TaxCalculationStrategy


AVATAX_PLUGIN_ID = "mirumee.taxes.avalara"
VATLAYER_ID = "mirumee.taxes.vatlayer"

CHECKOUT_CALCULATE_TAXES = "checkout_calculate_taxes"
ORDER_CALCULATE_TAXES = "order_calculate_taxes"


def add_tax_configuration_for_channels(apps, schema_editor):
    Channel = apps.get_model("channel", "Channel")
    TaxConfiguration = apps.get_model("tax", "TaxConfiguration")
    SiteSettings = apps.get_model("site", "SiteSettings")

    site_settings = SiteSettings.objects.first()
    tax_configurations = []

    for channel in Channel.objects.all():
        # For US channels create a configuration that's meaningful in US, where prices
        # as entered and displayed without tax.
        if channel.default_country == "US":
            display_gross_prices = False
            prices_entered_with_tax = False
        else:
            display_gross_prices = site_settings.display_gross_prices
            prices_entered_with_tax = site_settings.include_taxes_in_prices

        tax_configuration = TaxConfiguration(
            channel=channel,
            charg