# Generated by Django 3.1 on 2020-10-30 11:28

import django.db.models.deletion
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0136_add_attribute_type_and_page_to_attribute_