# Generated by Django 1.9.1 on 2016-02-04 17:07
from __future__ import unicode_literals

import datetime
import os

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_auto_20160129_0826"),
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                 