# Generated by Django 1.9.1 on 2016-02-07 11:34
from __future__ import unicode_literals

import datetime
import os

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("discount", "0002_voucher")]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="type",
            field=models.CharField(
                choices=[
                    ("fixed", os.environ.get("DEFAULT_CURRENCY", "USD")),
                    ("percentage", "%"),
                ],
                default="fix