# Generated by Django 3.1.5 on 2021-02-05 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0097_auto_20210107_1148"),
        ("discount", "0023_voucher_channel_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDiscount",
            fields=[
                (
 