
# Generated by Django 2.0.2 on 2018-02-10 10:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0039_auto_20180312_1203")]

    operations = [
        migrations.CreateModel(
            name="Fulfillment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,