# Generated by Django 3.2.6 on 2021-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0114_alter_order_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("af", "Afrikaans"),
                    ("af-na", "Afrikaans (Namibia)"),
                    ("af-za", "Afrikaans (South Africa)"),
                    ("agq", "Aghem"),
                    ("agq-cm", "Aghem (Cameroon)"),
                    ("ak", "Akan"),
                    ("ak-gh", "Akan (Ghana)"),
                    ("am", "Amharic"),
                    ("am-et", "Amharic (Ethiopia)"),
                    ("ar", "Arabic"),
                    ("ar-ae", "Arabic (United Arab Emirates)"),
                    ("ar-bh", "Arabic (Bahrain)"),
                    ("ar-dj", "Arabic (Djibouti)"),
                    ("ar-dz", "Arabic (Algeria)"),
                    ("ar-eg", "Arabic (Egypt)"),
                    ("ar-eh", "Arabic (Western Sahara)"),
                    ("ar-er", "Arabic (Eritrea)"),
                    ("ar-il", "Arabic (Israel)"),
                    ("ar-iq", "Arabic (Iraq)"),
                    ("ar-jo", "Arabic (Jordan)"),
                    ("ar-km", "Arabic (Comoros)"),
                    ("ar-kw", "Arabic (Kuwait)"),
                    ("ar-lb", "Arabic (Lebanon)"),
                    ("ar-ly", "Arabic (Libya)"),
                    ("ar-ma", "Arabic (Morocco)"),
                    ("ar-mr", "Arabic (Mauritania)"),
                    ("ar-om", "Arabic (Oman)"),
                    ("ar-ps", "Arabic (Palestinian Territories)"),
                    ("ar-qa", "Arabic (Qatar)"),
                    ("ar-sa", "Arabic (S