# Generated by Django 2.2.4 on 2019-09-05 10:10

import django.contrib.postgres.fields.jsonb
import oauthlib.common
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.M