# Generated by Django 3.2.16 on 2022-11-29 09:50

from django.db import migrations, models
import saleor.account.models


# Forward helpers
def rename_group_tables(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    schema_editor.alter_db_table(
        Group,
        "auth_group",
        "account_group",
    )
    PermissionGroup = Group.permissions.through
    schema_editor.alter_db_table(
        PermissionGroup,
        "auth_group_permissions",
        "account_group_permissions",
    )


RENAME_CONSTRAINTS_AND_INDEX = """
ALTER TABLE account_group RENAME CONSTRAINT auth_group_pkey
    TO account_group_pkey;

ALTER TABLE account_group RENAME CONSTRAINT auth_group_name_key
    TO account_group_name_key;

ALTER INDEX IF EXISTS auth_group_name_a6ea08ec_like
    RENAME TO account_group_name_034e9f3f_like;
"""


# Reverse helpers
def rename_group_tables_reverse(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    schema_editor.alter_db_table(
        Group,
        "account_group",
        "auth_group",
    )
    PermissionGroup = Group.permissions.through
    schema_editor.alter_db_table(
        PermissionGroup,
        "account_group_permissions",
        "auth_group_permissions",
    )


RENAME_CONSTRAINTS_AND_INDEX_REVERSE = """
ALTER TABLE account_group RENAME CONSTRAINT account_group_pkey
    TO auth_group_pkey;

ALTER TABLE account_group RENAME CONSTRAINT account_group_name_key
    TO auth_group_name_key;

ALTER INDEX IF EXIST