# Generated by Django 3.2.16 on 2023-01-10 08:39

import django.contrib.postgres.indexes
from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0074_merge_20230102_0914"),
   