"""List of all languages supported in Saleor.

Generated with Babel:

from babel import Locale
from babel.localedata import locale_identifiers

EXCLUDE = [
    "ar_001",
    "en_US_POSIX",
    "en_001",
    "en_150",
    "eo_001",
    "es_419",
    "ia_001",
    "prg_001",
    "vo_001",
    "yi_001",
]

languages = []

for lid in sorted(locale_identifiers()):
    if lid not in EXCLUDE:
        languages.append((lid.replace("_", "-"), Locale.parse(lid).english_name))
"""


LANGUAGES = [
    ("af", "Afrikaans"),
    ("af-na", "Afrikaans (Namibia)"),
    ("af-za", "Afrikaans (South Africa)"),
    ("agq", "Aghem"),
    ("agq-cm", "Aghem (Cameroon)"),
    ("ak", "Akan"),
    ("ak-gh", "Akan (Ghana)"),
    ("am", "Amharic"),
    ("am-et", "Amharic (Ethiopia)"),
    ("ar", "Arabic"),
    ("ar-ae", "Arabic (United Arab Emirates)"),
    ("ar-bh", "Arabic (Bahrain)"),
    ("ar-dj", "Arabic (Djibouti)"),
    ("ar-dz", "Arabic (Algeria)"),
    ("ar-eg", "Arabic (Egypt)"),
    ("ar-eh", "Arabic (Western Sahara)"),
    ("ar-er", "Arabic (Eritrea)"),
    ("ar-il", "Arabic (Israel)"),
    ("ar-iq", "Arabic (Iraq)"),
    ("ar-jo", "Arabic (Jordan)"),
    ("ar-km", "Arabic (Comoros)"),
    ("ar-kw", "Arabic (Kuwait)"),
    ("ar-lb", "Arabic (Lebanon)"),
    ("ar-ly", "Arabic (Libya)"),
    ("ar-ma", "Arabic (Morocco)"),
    ("ar-mr", "Arabic (Mauritania)"),
    ("ar-om", "Arabic (Oman)"),
    ("ar-ps", "Arabic (Palestinian Territories)"),
    ("ar-qa", "Arabic (Qatar)"),
    ("ar-sa", "Arabic (Saudi Arabia)"),
    ("ar-sd", "Arabic (Sudan)"),
    ("ar-so", "Arabic (Somalia)"),
    ("ar-ss", "Arabic (South Sudan)"),
    ("ar-sy", "Arabic (Syria)"),
    ("ar-td", "Arabic (Chad)"),
    ("ar-tn", "Arabic (Tunisia)"),
    ("ar-ye", "Arabic (Yemen)"),
    ("as", "Assamese"),
    ("as-in", "Assamese (India)"),
    ("asa", "Asu"),
    ("asa-tz", "Asu (Tanzania)"),
    ("ast", "Asturian"),
    ("ast-es", "Asturian (Spain)"),
    ("az", "Azerbaijani"),
    ("az-cyrl", "Azerbaijani (Cyrillic)"),
    ("az-cyrl-az", "Azerbaijani (Cyrillic, Azerbaijan)"),
    ("az-latn", "Azerbaijani (Latin)"),
    ("az-latn-az", "Azerbaijani (Latin, Azerbaijan)"),
    ("bas", "Basaa"),
    ("bas-cm", "Basaa (Cameroon)"),
    ("be", "Belarusian"),
    ("be-by", "Belarusian (Belarus)"),
    ("bem", "Bemba"),
    ("bem-zm", "Bemba (Zambia)"),
    ("bez", "Bena"),
    ("bez-tz", "Bena (Tanzania)"),
    ("bg", "Bulgarian"),
    ("bg-bg", "Bulgarian (Bulgaria)"),
    ("bm", "Bambara"),
    ("bm-ml", "Bambara (Mali)"),
    ("bn", "Bangla"),
    ("bn-bd", "Bangla (Bangladesh)"),
    ("bn-in", "Bangla (India)"),
    ("bo", "Tibetan"),
    ("bo-cn", "Tibetan (China)"),
    ("bo-in", "Tibetan (India)"),
    ("br", "Breton"),
    ("br-fr", "Breton (France)"),
    ("brx", "Bodo"),
    ("brx-in", "Bodo (India)"),
    ("bs", "Bosnian"),
    ("bs-cyrl", "Bosnian (Cyrillic)"),
    ("bs-cyrl-ba", "Bosnian (Cyrillic, Bosnia & Herzegovina)"),
    ("bs-latn", "Bosnian (Latin)"),
    ("bs-latn-ba", "Bosnian (Latin, Bosnia & Herzegovina)"),
    ("ca", "Catalan"),
    ("ca-ad", "Catalan (Andorra)"),
    ("ca-es", "Catalan (Spain)"),
    ("ca-es-valencia", "Catalan (Spain, Valencian)"),
    ("ca-fr", "Catalan (France)"),
    ("ca-it", "Catalan (Italy)"),
    ("ccp", "Chakma"),
    ("ccp-bd", "Chakma (Bangladesh)"),
    ("ccp-in", "Chakma (India)"),
    ("ce", "Chechen"),
    ("ce-ru", "Chechen (Russia)"),
    ("ceb", "Cebuano"),
    ("ceb-ph", "Cebuano (Philippines)"),
    ("cgg", "Chiga"),
    ("cgg-ug", "Chiga (Uganda)"),
    ("chr", "Cherokee"),
    ("chr-us", "Cherokee (United States)"),
    ("ckb", "Central Kurdish"),
    ("ckb-iq", "Central Kurdish (Iraq)"),
    ("ckb-ir", "Central Kurdish (Iran)"),
    ("cs", "Czech"),
    ("cs-cz", "Czech (Czechia)"),
    ("cu", "Church Slavic"),
    ("cu-ru", "Church Slavic (Russia)"),
    ("cy", "Welsh"),
    ("cy-gb", "Welsh (United Kingdom)"),
    ("da", "Danish"),
    ("da-dk", "Danish (Denmark)"),
    ("da-gl", "Danish (Greenland)"),
    ("dav", "Taita"),
    ("dav-ke", "Taita (Kenya)"),
    ("de", "German"),
    ("de-at", "German (Austria)"),
    ("de-be", "German (Belgium)"),
    ("de-ch", "German (Switzerland)"),
    ("de-de", "German (Germany)"),
    ("de-it", "German (Italy)"),
    ("de-li", "German (Liechtenstein)"),
    ("de-lu", "German (Luxembourg)"),
    ("dje", "Zarma"),
    ("dje-ne", "Zarma (Niger)"),
    ("dsb", "Lower Sorbian"),
    ("dsb-de", "Lower Sorbian (Germany)"),
    ("dua", "Duala"),
    ("dua-cm", "Duala (Cameroon)"),
    ("dyo", "Jola-Fonyi"),
    ("dyo-sn", "Jola-Fonyi (Senegal)"),
    ("dz", "Dzongkha"),
    ("dz-bt", "Dzongkha (Bhutan)"),
    ("ebu", "Embu"),
    ("ebu-ke", "Embu (Kenya)"),
    ("ee", "Ewe"),
    ("ee-gh", "Ewe (Ghana)"),
    ("ee-tg", "Ewe (Togo)"),
    ("el", "Greek"),
    ("el-cy", "Greek (Cyprus)"),
    ("el-gr", "Greek (Greece)"),
    ("en", "English"),
    ("en-ae", "English (United Arab Emirates)"),
    ("en-ag", "English (Antigua & Barbuda)"),
    ("en-ai", "English (Anguilla)"),
    ("en-as", "English (American Samoa)"),
    ("en-at", "English (Austria)"),
    ("en-au", "English (Australia)"),
    ("en-bb", "English (Barbados)"),
    ("en-be", "English (Belgium)"),
    ("en-bi", "English (Burundi)"),
    ("en-bm", "English (Bermuda)"),
    ("en-bs", "English (Bahamas)"),
    ("en-bw", "English (Botswana)"),
    ("en-bz", "English (Belize)"),
    ("en-ca", "English (Canada)"),
    ("en-cc", "English (Cocos (Keeling) Islands)"),
    ("en-ch", "English (Switzerland)"),
    ("en-ck", "English (Cook Islands)"),
    ("en-cm", "English (Cameroon)"),
    ("en-cx", "English (Christmas Island)"),
    ("en-cy", "English (Cyprus)"),
    ("en-de", "English (Germany)"),
    ("en-dg", "English (Diego Garcia)"),
    ("en-dk", "English (Denmark)"),
    ("en-dm", "English (Dominica)"),
    ("en-er", "English (Eritrea)"),
    ("en-fi", "English (Finland)"),
    ("en-fj", "English (Fiji)"),
    ("en-fk", "English (Falkland Islands)"),
    ("en-fm", "English (Micronesia)"),
    ("en-gb", "English (United Kingdom)"),
    ("en-gd", "English (Grenada)"),
    ("en-gg", "English (Guernsey)"),
    ("en-gh", "English (Ghana)"),
    ("en-gi", "English (Gibraltar)"),
    ("en-gm", "English (Gambia)"),
    ("en-gu", "English (Guam)"),
    ("en-gy", "English (Guyana)"),
    ("en-hk", "English (Hong Kong SAR China)"),
    ("en-ie", "English (Ireland)"),
    ("en-il", "English (Israel)"),
    ("en-im", "English (Isle of Man)"),
    ("en-in", "English (India)"),
    ("en-io", "English (British Indian Ocean Territory)"),
    ("en-je", "English (Jersey)"),
    ("en-jm", "English (Jamaica)"),
    ("en-ke", "English (Kenya)"),
    ("en-ki", "English (Kiribati)"),
    ("en-kn", "English (St. Kitts & Nevis)"),
    ("en-ky", "English (Cayman Islands)"),
    ("en-lc", "English (St. Lucia)"),
    ("en-lr", "English (Liberia)"),
    ("en-ls", "English (Lesotho)"),
    ("en-mg", "English (Madagascar)"),
    ("en-mh", "English (Marshall Islands)"),
    ("en-mo", "English (Macao SAR China)"),
    ("en-mp", "English (Northern Mariana Islands)"),
    ("en-ms", "English (Montserrat)"),
    ("en-mt", "English (Malta)"),
    ("en-mu", "English (Mauritius)"),
    ("en-mw", "English (Malawi)"),
    ("en-my", "English (Malaysia)"),
    ("en-na", "English (Namibia)"),
    ("en-nf", "English (Norfolk Island)"),
    ("en-ng", "English (Nigeria)"),
    ("en-nl", "English (Netherlands)"),
    ("en-nr", "English (Nauru)"),
    ("en-nu", "English (Niue)"),
    ("en-nz", "English (New Zealand)"),
    ("en-pg", "English (Papua New Guinea)"),
    ("en-ph", "English (Philippines)"),
    ("en-pk", "English (Pakistan)"),
    ("en-pn", "English (Pitcairn Islands)"),
    ("en-pr", "English (Puerto Rico)"),
    ("en-pw", "English (Palau)"),
    ("en-rw", "English (Rwanda)"),
    ("en-sb", "English (Solomon Islands)"),
    ("en-sc", "English (Seychelles)"),
    ("en-sd", "English (Sudan)"),
    ("en-se", "English (Sweden)"),
    ("en-sg", "English (Singapore)"),
    ("en-sh", "English (St. Helena)"),
    ("en-si", "English (Slovenia)"),
    ("en-sl", "English (Sierra Leone)"),
    ("en-ss", "English (South Sudan)"),
    ("en-sx", "English (Sint Maarten)"),
    ("en-sz", "English (Eswatini)"),
    ("en-tc", "English (Turks & Caicos Islands)"),
    ("en-tk", "English (Tokelau)"),
    ("en-to", "English (Tonga)"),
    ("en-tt", "English (Trinidad & Tobago)"),
    ("en-tv", "English (Tuvalu)"),
    ("en-tz", "English (Tanzania)"),
    ("en-ug", "English (Uganda)"),
    ("en-um", "English (U.S. Outlying Islands)"),
    ("en-us", "English (United States)"),
    ("en-vc", "English (St. Vincent & Grenadines)"),
    ("en-vg", "English (British Virgin Islands)"),
    ("en-vi", "English (U.S. Virgin Islands)"),
    ("en-vu", "English (Vanuatu)"),
    ("en-ws", "English (Samoa)"),
    ("en-za", "English (South Africa)"),
    ("en-zm", "English (Zambia)"),
    ("en-zw", "English (Zimbabwe)"),
    ("eo", "Esperanto"),
    ("es", "Spanish"),
    ("es-ar", "Spanish (Argentina)"),
    ("es-bo", "Spanish (Bolivia)"),
    ("es-br", "Spanish (Brazil)"),
    ("es-bz", "Spanish (Belize)"),
    ("es-cl", "Spanish (Chile)"),
    ("es-co", "Spanish (Colombia)"),
    ("es-cr", "Spanish (Costa Rica)