# Generated by Django 3.2.15 on 2023-01-04 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0016_alter_giftcard_created_at"),
    ]

    oper